/*
TextHive Core API

Testing MessagesApiService

*/

// Code generated by Konfig (https://konfigthis.com);

package texthive

import (
	"testing"
	// "github.com/stretchr/testify/assert"
	// "github.com/stretchr/testify/require"
	// texthive "github.com/texthive/text-sdks/go"
)

func Test_texthive_MessagesApiService(t *testing.T) {

	// configuration := texthive.NewConfiguration()
	// configuration.SetHost("http://127.0.0.1:4010")
	/*
	   configuration.SetApiKey("X_API_KEY")
	   client := texthive.NewAPIClient(configuration)
	*/

	t.Run("Test MessagesApiService SendMessageToContact", func(t *testing.T) {
		/* TODO: ENG-1367 Fix parameter values for Go SDK generated tests

		   sendMessageToContactRequest := *texthive.NewSendMessageToContactRequest(
		       "null",
		       "null",
		       "null",
		   )

		   request := client.MessagesApi.SendMessageToContact(
		       sendMessageToContactRequest,
		   )

		   resp, httpRes, err := request.Execute()

		   require.Nil(t, err)
		   require.NotNil(t, resp)
		   assert.Equal(t, 200, httpRes.StatusCode)
		*/
	})

	t.Run("Test MessagesApiService SendMessageToPhoneNumber", func(t *testing.T) {
		/* TODO: ENG-1367 Fix parameter values for Go SDK generated tests

		   sendMessageToPhoneNumberRequest := *texthive.NewSendMessageToPhoneNumberRequest(
		       "null",
		       "null",
		       "null",
		   )

		   request := client.MessagesApi.SendMessageToPhoneNumber(
		       sendMessageToPhoneNumberRequest,
		   )

		   resp, httpRes, err := request.Execute()

		   require.Nil(t, err)
		   require.NotNil(t, resp)
		   assert.Equal(t, 200, httpRes.StatusCode)
		*/
	})

}
