/*
TextHive Core API

Testing TemplatesApiService

*/

// Code generated by Konfig (https://konfigthis.com);

package texthive

import (
	"testing"
	// "github.com/stretchr/testify/assert"
	// "github.com/stretchr/testify/require"
	// texthive "github.com/texthive/text-sdks/go"
)

func Test_texthive_TemplatesApiService(t *testing.T) {

	// configuration := texthive.NewConfiguration()
	// configuration.SetHost("http://127.0.0.1:4010")
	/*
	   configuration.SetApiKey("X_API_KEY")
	   client := texthive.NewAPIClient(configuration)
	*/

	t.Run("Test TemplatesApiService CreateTemplate", func(t *testing.T) {
		/* TODO: ENG-1367 Fix parameter values for Go SDK generated tests

		   templateCreateRequest := *texthive.NewTemplateCreateRequest(
		       "null",
		       "null",
		   )

		   request := client.TemplatesApi.CreateTemplate(
		       templateCreateRequest,
		   )

		   resp, httpRes, err := request.Execute()

		   require.Nil(t, err)
		   require.NotNil(t, resp)
		   assert.Equal(t, 200, httpRes.StatusCode)
		*/
	})

	t.Run("Test TemplatesApiService GetTemplatesForCustomer", func(t *testing.T) {
		/* TODO: ENG-1367 Fix parameter values for Go SDK generated tests
		   request := client.TemplatesApi.GetTemplatesForCustomer(
		       ""38400000-8cf0-11bd-b23e-10b96e4ef00d"",
		   )

		   resp, httpRes, err := request.Execute()

		   require.Nil(t, err)
		   require.NotNil(t, resp)
		   assert.Equal(t, 200, httpRes.StatusCode)
		*/
	})

}
