/*
 * TextHive Core API
 *
 * TextHive is a unified messaging API that enables developers to seamlessly send messages across multiple channels including SMS and WhatsApp. It provides programmatic management of customer accounts, messaging capabilities with intelligent routing, message delivery, and template management. The API supports creating, updating, and managing customer profiles, sending messages using templates, retrieving contact information, and handling templates across different messaging channels.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: developers@texthive.khulnasoft.com
 * Generated by: https://konfigthis.com
 */


using System;
using Xunit;
using Texthive.Net.Client;
using Texthive.Net.Model;

namespace Texthive.Net.Test
{
    /// <remarks>
    /// Boilerplate for writing some simple tests
    /// </remarks>
    public class SimpleTests : IDisposable
    {
        public SimpleTests()
        {
            // Setup
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test Client Initialization
        /// </summary>
        [Fact]
        public void ClientTest()
        {
            Texthive client = new Texthive();
            // Configure API key authorization: ApiKey
            client.SetApiKey("YOUR_API_KEY");
            // Configure token for authorization
            client.SetAccessToken("YOUR_TOKEN");

            Assert.NotNull(client);
        }
    }
}
